#!/usr/bin/perl

use strict;
use warnings;

use File::Temp qw/tempdir/;


my $tmpdir = tempdir(CLEANUP => 1);

$ENV{PGHOST} = $tmpdir;
$ENV{PGPORT} = 54321;
$ENV{PGDATA} = $tmpdir."/pgdata";
$ENV{PGUSER} = 'postgres';

my $ret;

system 'initdb -A trust -U postgres >/dev/null';
$ret = system 'pg_ctl', '-s', '-w', '-l', "$tmpdir/logfile", '-o', "--fsync=off -k $tmpdir --listen-addresses=''", 'start';

if ($ret != 0) {
    system('cat', "$tmpdir/logfile");
    exit 88;
}

$ret = system @ARGV;

system 'pg_ctl', '-s', '-w', '-m', 'immediate', 'stop';

if ($ret == -1) {
    exit 254;
} elsif ($ret & 127) {
    exit 255;
} else {
    exit $ret >> 8;
}
